version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 247606490890.dkr.ecr.us-east-1.amazonaws.com
      - echo "Build environment architecture:"
      - uname -m
      - docker version
      - docker buildx create --use --name mybuilder || docker buildx use mybuilder

  build:
    commands:
      - echo Building and pushing linux/amd64 image...
      - docker buildx build --platform linux/amd64 -t 247606490890.dkr.ecr.us-east-1.amazonaws.com/2048-gamerepo:latest --push .

  post_build:
    commands:
      - echo Creating imagedefinitions.json file for ECS deployment...
      - printf '[{"name":"2048-container","imageUri":"%s"}]' 247606490890.dkr.ecr.us-east-1.amazonaws.com/2048-gamerepo:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
