version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 148524399424.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 2048-game .
      - echo Tagging the Docker image...
      - docker tag 2048-gamerepo:latest 247606490890.dkr.ecr.us-east-1.amazonaws.com/2048-gamerepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 148524399424.dkr.ecr.us-east-1.amazonaws.com/newrepo:latest
      - echo Creating imagedefinitions.json file for ECS deployment...
      - echo '[{"name":"cont1","imageUri":"148524399424.dkr.ecr.us-east-1.amazonaws.com/newrepo:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json 
